static const uint8_t musicList[][2][20] PROGMEM = {
  { "Sample256kbps", "N_O_N_1.wav" },
  { "Sample128kbps", "N_O_N_3.wav" },
  { "Sample64kbps", "N_O_N_2.wav" },
  { "Bad_Apple!", "B_A_3.wav" },
  { "NightOfKnights", "N_O_N_1.wav" },
  { "BloodOnBlood", "blood.wav" },
  { "SyouzyoSatori", "satori.wav" },
  { "IsSheUNOwen", "UN_O.wav" },
  { "JudgmentOfDolls", "j_o_d.wav" },
  { "NoLifeQueen", "NLQ.wav" },
  { "SMHantei", "inubok_3.wav" },
  { "SweetsParade", "karuta_1.wav" },
  { "RenaiCirculation", "sengok_1.wav" },
  { "Mousou", "Mousou.wav" },
  { "YotugiDole", "yotugi.wav" },
  { "Kaerimiti", "kaeri.wav" },
  { "StapleStable", "Sta_Sta.wav" },
  { "PlatinumDisco", "PlaDis.wav" },
  { "NiseMonoED", "NiseED.wav" },
  { "SenbonZakura", "senbon.wav" },
  { "GakkoGurashi", "Gakko.wav"},
  { "KumamikoDancing", "Kuma.wav"},
  {"YoujoSenkiED", "Youjo.wav"},
  {"ZenZenZense", "Zense.wav"},
  {"YoukosoJapariParkE", "Kemono.wav"},
  {"InocentFlower", "Inocen.wav"},
  {"GabrielDropout", "Droout.wav"},
  {"Miiro", "Miiro.wav"},
  { "Kaizi1", "kaizi_1.wav" },
  { "Monogatari1", "bake_1.wav" },
  { "Monogatari2", "bake_2.wav" },
  { "Monogatari9", "Bake9.wav" },
  { "Monogatari10", "Bake10.wav" },
  {"Monogatari2-12", "M212.wav"},
  {"Monogatari2-14", "M214.wav"},
  {"Monogatari2-15", "M215.wav"},
  {"Monogatari2-25", "M225.wav"},
  {"Monogatari2-26", "M226.wav"},
  {"Koyomi5", "Koyo5.wav"},
  { "TukiMonoCom3", "TukiCom.wav" },
  { "PrisonSchool1", "P_S_1.wav" },
  { "PrisonSchool2", "P_S_2.wav" },
  { "PrisonSchool3", "P_S_3.wav" },
  { "PrisonSchool4", "P_S_4.wav" },
  { "PrisonSchool10", "P_S_10.wav" },
  { "PrisonSchool11", "P_S_11.wav" },
  { "PrisonSchool12", "P_S_12.wav" },
  { "PrisonSchoolOVA", "PSO.wav" },
};
